### ISSUE TITLE
Retirement of Centos 7, mirrorlist.centos.org not found

### ISSUE THREAD

**Issue by nathanlcarlson** [voxpupuli/beaker-docker#144]
mirrorlist.centos.org has been retired with the EOL of CentOS 7. This is causing trouble with CentOS7 and 8 runs.

For example: https://github.com/jhoblitt/puppet-ipmi/actions/runs/10813805325/job/30001421615?pr=78

**Comment by ekohl** [comment]
This isn't a problem with beaker-docker. We have [puppet_metadata](https://github.com/voxpupuli/puppet_metadata) to generate the matrix and since [version 4.0.0](https://github.com/voxpupuli/puppet_metadata/blob/master/CHANGELOG.md#400-2024-05-08) we automatically skip EOL OSes. I'd recommend that the repo is updated to that version.

**Comment by nathanlcarlson** [comment]
Thanks!
